stages:
    - verify
    - deploy

PHPCS:PHP7.2:MySQL:
    stage: verify
    image: wpunit/php:wpcs
    script:
        - phpcs

Deploy:
    stage: deploy
    environment: 
        name: deployment
    image: gagan0123/svn:latest
    when: manual
    script:
        - bash bin/release-plugin.sh